### ISSUE TITLE
[FEATURE] Adding documentation to Smithy models

### ISSUE THREAD

**Issue by Tokesh** [opensearch-project/opensearch-api-specification#118]
This issue covers Fill in API Reference URL for models listed below:

- [x] _global
- [x] cat
- [ ] cluster
- [ ] dangling_indices
- [ ] indices
- [x] nodes
- [x] remote_store/restore
- [x] snapshot
- [x] tasks

We discussed about this enhancement with @nhtruong on CCI meetup
We will be ready to do this together with @aabeshov after the merge of these models #106

**Comment by VachaShah** [comment]
This is great, thanks @Tokesh and @aabeshov!

**Comment by dblock** [comment]
Closing this one. Reopen new issues for anything missing that wasn't added.
