### ISSUE TITLE
Add Api definitions for create, get, and delete data_stream

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#129]
This is part of the `index_management` plugin that have now been added to OS as core features in the `indices` namespace, so the operation groups of these actions would be
`indices.create_data_stream`
`indices.get_data_stream`
`indices.delete_data_stream`

https://opensearch.org/docs/latest/im-plugin/data-streams/

**Comment by Tokesh** [comment]
I'd like to work on this issue :)
I'm already read this article about data streams. I think i have only one question about create_data_stream API.
In article they gave us such examples:
PUT _data_stream/logs-redis
PUT _data_stream/logs-nginx
Are "logs-redis" and "logs-nginx" just indexes, not index_templates?

**Comment by nhtruong** [comment]
`A data stream is internally composed of multiple backing indexes. Search requests are routed to all the backing indexes, while indexing requests are routed to the latest write index.`

So it makes sense that you need an index_template (it's like grepping for indices with similar names) to create a data-stream, since a data-stream is a collection of indices.

**Comment by nhtruong** [comment]
@Tokesh Looks like even though these endpoints were part of the legacy `index_management` plug-in. They have been added to OS as core features of the `indices` namespace. I've update the Issue's description to reflect that.

**Comment by Tokesh** [comment]
> So it makes sense that you need an index_template (it's like grepping for indices with similar names) to create a data-stream, since a data-stream is a collection of indices.

> @Tokesh Looks like even though these endpoints were part of the legacy `index_management` plug-in. They have been added to OS as core features of the `indices` namespace. I've update the Issue's description to reflect that.

Thank you so much for answers. I got it!

**Comment by Xtansia** [comment]
Closing as #131 was merged
