### ISSUE TITLE
[FEATURE] Support for wait_for_completion flag in force merge API

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/opensearch-api-specification#152]
### Is your feature request related to a problem?
Currently the force merge api in the client waits for force_merge to get completed. But OpenSearch provides a way where if we pass wait_for_completion = true, it gives a task id and poll the task id to see if the force merge is completed or not.

### What solution would you like?
Add the support for wait_for_completion flag in force merge api.

```
POST /hotels-index/_forcemerge?max_num_segments=1&wait_for_completion=true
```

### What alternatives have you considered?
The only other way is to send Raw HTTP request, but the domain is backed with security creating raw HTTP request is very difficult and not feasible.

### Do you have any additional context?
NA

**Comment by VachaShah** [comment]
The parameter has been added in the spec via PR #180. @saimedhi The python client can be regenerated to incorporate the changes.

**Comment by VachaShah** [comment]
Updated OpenAPI specs in #181
