### ISSUE TITLE
[BUG] Missing request body for delete_put, cat.pit_segments, action group, etc.

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-api-specification#159]
### What is the bug?
Request body description missing for "delete_pit", 
Request body description missing for "cat.pit_segments", 

and also several other security client APIs have body and path param descriptions missing
"security.change_password", "create_action_group", "patch_action_group"("action_group"path param description is also missing),  "patch_action_groups", ....

**Comment by dblock** [comment]
I opened a meta issue for descriptions, there's lots more.

https://github.com/opensearch-project/opensearch-api-specification/issues/403
