### ISSUE TITLE
[BUG] Missing definitions of common/global parameters

### ISSUE THREAD

**Issue by Xtansia** [opensearch-project/opensearch-api-specification#167]
### What is the bug?
There are a handful of query parameters which are common across the whole OpenSearch REST API. These are missing from the Smithy specifications, in the legacy spec they were defined in a separate `_common.json` file: https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/api/_common.json
See also: https://opensearch.org/docs/latest/api-reference/common-parameters/

These need to be added to the spec and preferably attributed as common/global in some manner, as at least the .NET client lifts these to a super class of all requests.

**Comment by nhtruong** [comment]
@Xtansia to clarify, we're not going to make every operation explicitly reference these query params right?
We can include this in `components.parameters` of the [root file](https://github.com/opensearch-project/opensearch-api-specification/blob/main/spec/OpenSearch.openapi.yaml).

**Comment by Xtansia** [comment]
@nhtruong For the specification to be true to the API they need to be included in all operations one way or another. Can have them injected into each operation/path as part of the merging to the final spec to save having to hand write them in every spec file?

**Comment by nhtruong** [comment]
Having it injected into single-file spec is a great idea since the filed is not meant to be read by humans anyway. Will update the merger to handle that.

**Comment by nhtruong** [comment]
I think we should also add some form of extension to tell the generators that these params should be accepted when the user pass it to the method but we don't need to list document them in every method description.
