### ISSUE TITLE
[PROPOSAL] search_after parameter added to _search, _msearch specifications

### ISSUE THREAD

**Issue by channel-dante** [opensearch-project/opensearch-api-specification#173]
### What are you proposing?
_search, _msearch can be received as an after_search parameter in the actual code, but it is not expressed on the specification information page.

**Comment by nhtruong** [comment]
Can you elaborate on `in the actual code`? Which code are we talking about?

**Comment by dblock** [comment]
@channel-dante We've made a lot of progress here. Any interest in filling out the API specs with tests for `_search` and `_msearch`?

**Comment by dblock** [comment]
The parameter is called `search_after`, https://opensearch.org/docs/latest/search-plugins/searching-data/paginate/#the-search_after-parameter
