### ISSUE TITLE
[FEATURE] Add specifications for plugins.

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-api-specification#178]
### Is your feature request related to a problem?

Sequentially introduce API specifications for plugins one by one. Feel free to expand the list with more plugins. (Can be done one plugin per PR)

- [ ] [Index State Management](https://opensearch.org/docs/latest/im-plugin/ism/api/)
- [ ] [Alerting](https://opensearch.org/docs/latest/observing-your-data/alerting/api/)
- [ ] [Snapshot Management](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/sm-api/)
- [ ] [Cross-cluster replication](https://opensearch.org/docs/latest/tuning-your-cluster/replication-plugin/api/)

The provided specifications contribute to resolving the following Python client issues:
https://github.com/opensearch-project/opensearch-py/issues/413
https://github.com/opensearch-project/opensearch-py/issues/143
https://github.com/opensearch-project/opensearch-py/issues/629

**Comment by dblock** [comment]
This is dup of https://github.com/opensearch-project/opensearch-api-specification/issues/168, which has the list of all the missing APIs.
