### ISSUE TITLE
[PROPOSAL] Require the OpenAPI spec to be re-generated for pull requests

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-api-specification#185]
### What are you proposing?

With the addition of coverage in #179 I propose we move the build into PRs as well.

1. Make `./gradlew build` output/overwrite `OpenSearch.openapi.json` at the root.
2. Make CI fail if that file is not up-to-date.

### What problems are you trying to solve?

Currently CI/CD re-generates the OpenAPI spec and makes a PR. This causes several issues.

- Warnings are ignored, whereas they should be errors (see #184).
- Coverage can't know what has changed next to the actual API spec change.
- We have 2 commits for every PR. 

### What is the developer experience going to be?

Require that developers run `./gradlew build` before a PR can be merged.

**Comment by nhtruong** [comment]
@dblock will https://github.com/opensearch-project/opensearch-api-specification/pull/211 resolve this one as well?

**Comment by dblock** [comment]
Yes, closing.
