### ISSUE TITLE
[PROPOSAL] Reduce the number of approvers required in this repo to 1

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-api-specification#199]
### What are you proposing?

Currently the number of approvers required to merge a CR in this repo is 2.

### What problems are you trying to solve?

This affects velocity unnecessarily. This repo doesn't have production impact and any potential mistake is easily undone.

![Screenshot 2024-03-12 at 3 54 13 PM](https://github.com/opensearch-project/opensearch-api-specification/assets/542335/e289b379-8fd9-4720-9aeb-797838532e01)

### What is the developer experience going to be?

Only 1 approver required instead of 2 for PRs.

### What will it take to execute?

If a majority of existing maintainers can +1 I'll lower this number.

**Comment by dblock** [comment]
@abhivka7
@harshavamsi
@pgtgrly
@sachetalva
@nhtruong
@Xtansia
@VachaShah

**Comment by Xtansia** [comment]
I'm in support of doing this 👍

**Comment by dblock** [comment]
@abhivka7 do you have an e-mail that works?

**Comment by nhtruong** [comment]
I'm in!

**Comment by VachaShah** [comment]
I am in!

**Comment by sachetalva** [comment]
👍

**Comment by dblock** [comment]
Looks like we have majority of maintainers agreeing to this, I made the change.
