### ISSUE TITLE
[BUG]Search API spec is missing `include_named_queries_score` param

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-api-specification#200]
### What is the bug?
Search API [spec](https://github.com/opensearch-project/opensearch-api-specification/blob/main/OpenSearch.openapi.json#L27285) is missing [include_named_queries_score](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java#L293) param. Param is recently introduced in [PR](https://github.com/opensearch-project/OpenSearch/pull/11626). implemented for versions 2.13.0 and above

### Do you have any additional context?
- Fixes https://github.com/opensearch-project/opensearch-py/issues/686#issuecomment-1995745636
- Related to opensearch yaml test https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/search/350_matched_queries.yml#L56

**Comment by saimedhi** [comment]
@Xtansia, could you please check if this [test](https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/search/350_matched_queries.yml#L56) is  working as expected in opensearch-net? It should run in OpenSearch 2.x and Main.

**Comment by Xtansia** [comment]
> @Xtansia, could you please check if this [test](https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/search/350_matched_queries.yml#L56) is working as expected in opensearch-net? It should run in OpenSearch 2.x and Main.

The .NET YAML test runner uses the low-level client which allows setting arbitrary query params rather than using the explicitly specified properties. Rust on the other hand does some heuristics and skips tests that use APIs or params that don't yet exist in the client.
