### ISSUE TITLE
[BUG]indices.forcemerge API spec is missing 'primary_only' param

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-api-specification#201]
What is the bug?
indices.forcemerge API [spec](https://github.com/opensearch-project/opensearch-api-specification/blob/main/OpenSearch.openapi.json#L8212) is missing [primary_only](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/rest/action/admin/indices/RestForceMergeAction.java#L79) param. Param is recently introduced in [PR](https://github.com/opensearch-project/OpenSearch/commit/e6eec36ccbdea99e7832d1b6a9c014d2cee1940a). "primary_only" is available in OpenSearch 3.0+ versions.

Do you have any additional context?

- Fixes https://github.com/opensearch-project/opensearch-py/issues/686#issuecomment-1995745636
- Related to yaml test https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/indices.forcemerge/10_basic.yml#L32

**Comment by saimedhi** [comment]
@Xtansia, could you please check if this [test]( https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/indices.forcemerge/10_basic.yml#L32) is working as expected in opensearch-net? It will run for OpenSearch Main.

**Comment by Xtansia** [comment]
> @Xtansia, could you please check if this [test](https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/indices.forcemerge/10_basic.yml#L32) is working as expected in opensearch-net? It will run for OpenSearch Main.

The .NET YAML test runner uses the low-level client which allows setting arbitrary query params rather than using the explicitly specified properties. Rust on the other hand does some heuristics and skips tests that use APIs or params that don't yet exist in the client.
