### ISSUE TITLE
[FEATURE] Lint API specs

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-api-specification#205]
### Is your feature request related to a problem?

In https://github.com/opensearch-project/opensearch-api-specification/pull/203 we renamed a path parameter from `NodeId` to `node_id` because it caused a downstream generator in the opensearch-py client to produce a camelCase parameter which was caught in a linter there and errored.

### What solution would you like?

A linter for consistency in the API spec for parameters, variables, etc.

### Do you have any additional context?

https://github.com/opensearch-project/opensearch-py/pull/700#issuecomment-2010365233

**Comment by nhtruong** [comment]
I will add this to the validator im working on as one of the follow up PRs.

**Comment by dblock** [comment]
Coming from https://github.com/opensearch-project/opensearch-api-specification/pull/218, linter should check description format (capitalized, full sentences with periods), and no line wrapping.
