### ISSUE TITLE
[FEATURE] Add CI

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-api-specification#21]
**Is your feature request related to a problem?**

Add CI that validates the models.

**What solution would you like?**
CI that runs on every PR that ensures models are at least valid.

**Comment by sachetalva** [comment]
Yes, we are working on a proposal for a CI to validate Smithy Models. The CI workflow will test out the models against an opensearch server to validate that the models match the api implementation.
Will update this thread with the CI proposal.

**Comment by SOPHIA2401** [comment]
Hi, @dblock.

For validating Smithy models, I proposed a CI framework. The following is the link to the proposal: https://github.com/opensearch-project/opensearch-api-specification/issues/33
