### ISSUE TITLE
[PROPOSAL] Rename OpenSearch.latest.yaml

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-api-specification#212]
### What are you proposing?

Rename OpenSearch.latest.yaml.

### What problems are you trying to solve?

The fact that we have two periods in the file name of the API spec (`OpenSearch.latest.yaml`) is, at the very least, unusual. 

### What is the developer experience going to be?

Rename the file. Some options:

1. OpenSearch.yml
2. opensearch.yml
3. OpenSearch-API.yml
4. opensearch-api.yml
5. something else?

#### Are there any breaking changes to the API

Yes, now is the right time to potentially rename this file because we're switching to OpenAPI (#208) and changing the build and release process in #211.

### What is the user experience going to be?

A file name that makes more sense.

#### Are there breaking changes to the User Experience?

The file name will change.

### Any remaining open questions?

Is there some kind of naming convention in other products?

**Comment by Xtansia** [comment]
As far as the specification is concerned, there's no hard rule or standard, just a recommendation here [https://spec.openapis.org/oas/v3.1.0#document-structure](https://spec.openapis.org/oas/v3.1.0#document-structure):
> It is RECOMMENDED that the root OpenAPI document be named: openapi.json or openapi.yaml.

**Comment by dblock** [comment]
There's some chance that we will be including other/separate OpenAPI specs in this repo (e.g. for plugins), so I think we should preserve "OpenSearch" in the name. The core repo is also called `OpenSearch`, but the spec includes plugins. Maybe we should match the lowercase of the distribution https://artifacts.opensearch.org/releases/bundle/opensearch/2.12.0/opensearch-2.12.0-linux-x64.tar.gz? When we release a versioned spec it should probably be called opensearch-openapi-2.12.0.yaml.

All this said, I think my current preference is **opensearch-openapi.yaml**.
