### ISSUE TITLE
[FEATURE] Add specs for `asynchronous_search` namespace

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#223]
Part of [Adding missing API specs issue](https://github.com/opensearch-project/opensearch-api-specification/issues/168)

- [ ] /_plugins/_asynchronous_search: ["POST"]
- [ ] /_plugins/_asynchronous_search/_nodes/{nodeId}/stats: ["GET"]
- [ ] /_plugins/_asynchronous_search/stats: ["GET"]
- [ ] /_plugins/_asynchronous_search/{id}: ["GET","DELETE"]

**Comment by Tokesh** [comment]
Hi! I would like to work on this issue! :)

**Comment by Tokesh** [comment]
I think we can close this issue by #525
