### ISSUE TITLE
[FEATURE] Add specs for `ism` namespace

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#224]
Part of [Adding missing API specs issue](https://github.com/opensearch-project/opensearch-api-specification/issues/168)

- [x] /_opendistro/_ism/add: ["POST"]
- [x] /_opendistro/_ism/add/{index}: ["POST"]
- [x] /_opendistro/_ism/change_policy: ["POST"]
- [x] /_opendistro/_ism/change_policy/{index}: ["POST"]
- [x] /_opendistro/_ism/explain: ["GET"]
- [x] /_opendistro/_ism/explain/{index}: ["GET"]
- [x] /_opendistro/_ism/policies: ["GET","PUT"]
- [x] /_opendistro/_ism/policies/{policyID}: ["GET","PUT","DELETE","HEAD"]
- [x] /_opendistro/_ism/remove: ["POST"]
- [x] /_opendistro/_ism/remove/{index}: ["POST"]
- [x] /_opendistro/_ism/retry: ["POST"]
- [x] /_opendistro/_ism/retry/{index}: ["POST"]
---
- [x] /_plugins/_ism/add: ["POST"]
- [x] /_plugins/_ism/add/{index}: ["POST"]
- [x] /_plugins/_ism/change_policy: ["POST"]
- [x] /_plugins/_ism/change_policy/{index}: ["POST"]
- [x] /_plugins/_ism/explain: ["GET"]
- [x] /_plugins/_ism/explain/{index}: ["GET"]
- [x] /_plugins/_ism/policies: ["GET","PUT"]
- [x] /_plugins/_ism/policies/{policyID}: ["GET","PUT","DELETE","HEAD"]
- [x] /_plugins/_ism/remove: ["POST"]
- [x] /_plugins/_ism/remove/{index}: ["POST"]
- [x] /_plugins/_ism/retry: ["POST"]
- [x] /_plugins/_ism/retry/{index}: ["POST"]
---
- [x] /_opendistro/_refresh_search_analyzers: ["POST"]
- [x] /_opendistro/_refresh_search_analyzers/{index}: ["POST"]
---
- [x] /_plugins/_refresh_search_analyzers: ["POST"]
- [x] /_plugins/_refresh_search_analyzers/{index}: ["POST"]

**Comment by dblock** [comment]
I started working on this in https://github.com/opensearch-project/opensearch-api-specification/pull/568.

**Comment by dblock** [comment]
> * /_plugins/_ism/add

Note that while the API seems to respond to this route, it will fail without indices, and there's no way to specify those in the body, https://github.com/opensearch-project/index-management/blob/main/src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/resthandler/RestAddPolicyAction.kt#L48.

**Comment by dblock** [comment]
After #578 the report shows these missing:

```
"/_plugins/_ism/remove": [
        "post"
      ],
      "/_plugins/_ism/retry": [
        "post"
      ],
      "/_plugins/_ism/change_policy": [
        "post"
      ],
      "/_plugins/_ism/add": [
        "post"
      ],
      "/_plugins/_ism/explain": [
        "post"
      ],
      "/_plugins/_ism/explain/{}": [
        "post"
      ],
      "/_plugins/_ism/policies": [
        "put"
      ],
```

I think these are a bug, they don't seem to take request objects in which you can specify enough parameters, but I'm still digging through the code.
