### ISSUE TITLE
[FEATURE] Add specs for `notifications` namespace

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#229]
Part of [Adding missing API specs issue](https://github.com/opensearch-project/opensearch-api-specification/issues/168)

- [ ] /_plugins/_notifications/channels: ["GET"]
- [ ] /_plugins/_notifications/configs: ["GET","POST","DELETE"]
- [ ] /_plugins/_notifications/configs/{config_id}: ["GET","PUT","DELETE"]
- [ ] /_plugins/_notifications/feature/test/{config_id}: ["GET","POST"]
- [ ] /_plugins/_notifications/features: ["GET"]

**Comment by spapadop** [comment]
After https://github.com/opensearch-project/opensearch-api-specification/pull/169 and https://github.com/opensearch-project/opensearch-api-specification/pull/217 I still see there is one API missing, as it's not listed on the [doc page](https://opensearch.org/docs/latest/observing-your-data/notifications/api/#get-channel-configuration).
`/_plugins/_notifications/channels: ["GET"]`. 

I could try adding it.

**Comment by spapadop** [comment]
there you go!
