### ISSUE TITLE
[FEATURE] Add a plugin model (e.g. job-scheduler)

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-api-specification#23]
**Is your feature request related to a problem?**
Scope seems to be limited to engine. Where and how does one add a model?

**What solution would you like?**
Add a model for a plugin, e.g. job-scheduler.
Document how to add a model for a new plugin.

**Comment by VachaShah** [comment]
Closing this issue since adding plugin models is now part of #168.
