### ISSUE TITLE
[FEATURE] Add specs for `observability` namespace

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#230]
Part of [Adding missing API specs issue](https://github.com/opensearch-project/opensearch-api-specification/issues/168)

- [ ] /_plugins/_observability/_local/stats: ["GET"]
- [ ] /_plugins/_observability/object: ["GET","POST","DELETE"]
- [ ] /_plugins/_observability/object/{objectId}: ["GET","PUT","DELETE"]
---
- [ ] /_plugins/_query/_datasources: ["GET","PUT","POST"]
- [ ] /_plugins/_query/_datasources/{dataSourceName}: ["GET","DELETE"]
- [ ] /_plugins/_query/settings: ["PUT"]

**Comment by aabeshov** [comment]
Hello , I'd like to work on this issue if it's still relevant.

**Comment by dblock** [comment]
It sure is! Please do contribute.
