### ISSUE TITLE
[FEATURE] Add specs for `ppl` namespace

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#231]
Part of [Adding missing API specs issue](https://github.com/opensearch-project/opensearch-api-specification/issues/168)

- [ ] /_opendistro/_ppl: ["POST"]
- [ ] /_opendistro/_ppl/_explain: ["POST"]
- [ ] /_opendistro/_ppl/stats: ["GET","POST"]
---
- [ ] /_plugins/_ppl: ["POST"]
- [ ] /_plugins/_ppl/_explain: ["POST"]
- [ ] /_plugins/_ppl/stats: ["GET","POST"]

**Comment by Tokesh** [comment]
Hello! I would like to work on this issue :)

**Comment by dblock** [comment]
Please!

**Comment by Tokesh** [comment]
I think we can close this issue by [#460]
