### ISSUE TITLE
[FEATURE] Add specs for `security` namespace

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#233]
Part of [Adding missing API specs issue](https://github.com/opensearch-project/opensearch-api-specification/issues/168)

- [ ] /_plugins/_security/api/actiongroup/: ["GET"]
- [ ] /_plugins/_security/api/actiongroup/{name}: ["GET","PUT","DELETE"]
- [ ] /_plugins/_security/api/actiongroups/: ["PATCH"]
- [ ] /_plugins/_security/api/allowlist: ["GET","PUT","PATCH"]
- [ ] /_plugins/_security/api/audit/: ["GET","PATCH"]
- [ ] /_plugins/_security/api/authtoken: ["POST"]
- [ ] /_plugins/_security/api/cache: ["GET","PUT","POST"]
- [ ] /_plugins/_security/api/internalusers/: ["GET","PATCH"]
- [ ] /_plugins/_security/api/internalusers/{name}/authtoken: ["POST"]
- [ ] /_plugins/_security/api/migrate: ["POST"]
- [ ] /_plugins/_security/api/permissionsinfo: ["GET"]
- [ ] /_plugins/_security/api/roles/: ["PATCH"]
- [ ] /_plugins/_security/api/rolesmapping/: ["GET","PATCH"]
- [ ] /_plugins/_security/api/ssl/{certType}/reloadcerts/: ["PUT"]
- [ ] /_plugins/_security/api/tenancy/config: ["GET","PUT"]
- [ ] /_plugins/_security/api/user/: ["GET"]
- [ ] /_plugins/_security/api/user/{name}: ["GET","PUT","DELETE"]
- [ ] /_plugins/_security/api/user/{name}/authtoken: ["POST"]
- [ ] /_plugins/_security/api/validate: ["GET"]
- [ ] /_plugins/_security/api/whitelist: ["GET","PUT","PATCH"]
- [ ] /_plugins/_security/authinfo: ["GET","POST"]
- [ ] /_plugins/_security/configupdate: ["PUT"]
- [ ] /_plugins/_security/dashboardsinfo: ["GET","POST"]
- [ ] /_plugins/_security/health: ["POST"]
- [ ] /_plugins/_security/tenantinfo: ["GET","POST"]
- [ ] /_plugins/_security/whoami: ["GET","POST"]
- [ ] /_plugins/_security/whoamiprotected: ["GET"]

**Comment by Jakob3xD** [comment]
@DarshitChanpura The AuthInfo component has arrays defined but no items. Is this expected?
https://github.com/opensearch-project/opensearch-api-specification/pull/271/files#diff-de67b1e2cc82107e6e0fa8ba31fa9dd04fd98e0bcabb9baacee71462748f6f0fR139-R147

**Comment by DarshitChanpura** [comment]
good catch.. these should have items present and they should be of string type. Let me fix that.
