### ISSUE TITLE
[FEATURE] Add specs for `sql` namespace

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#235]
Part of [Adding missing API specs issue](https://github.com/opensearch-project/opensearch-api-specification/issues/168)

- [ ] /_opendistro/_sql: ["POST"]
- [ ] /_opendistro/_sql/_explain: ["POST"]
- [ ] /_opendistro/_sql/close: ["POST"]
- [ ] /_opendistro/_sql/settings: ["PUT"]
- [ ] /_opendistro/_sql/stats: ["GET","POST"]
---
- [ ] /_plugins/_sql: ["POST"]
- [ ] /_plugins/_sql/_explain: ["POST"]
- [ ] /_plugins/_sql/close: ["POST"]
- [ ] /_plugins/_sql/stats: ["GET","POST"]

**Comment by Tokesh** [comment]
Hello everyone! I want to work on this issue :)

**Comment by Tokesh** [comment]
I think we can close this issue!
