### ISSUE TITLE
[FEATURE] Check order of methods in spec

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-api-specification#272]
### Is your feature request related to a problem?

Coming from https://github.com/opensearch-project/opensearch-api-specification/pull/271 where we reordered a DELETE method.

### What solution would you like?

A linter that orders methods (probably GET, POST, PUT, PATCH, DELETE).
 
### What alternatives have you considered?

Alphabetical order.

**Comment by nhtruong** [comment]
This should be applied to entire `spec` folder right?
We should also alow `--fix` option in the linter to auto fix issues like this.

**Comment by dblock** [comment]
@nhtruong Yes.

**Comment by nhtruong** [comment]
If someone else is picking this up: We already have a [helper function](https://github.com/opensearch-project/opensearch-api-specification/blob/main/tools/helpers.ts#L14-L28) that can do in-place object sorting with a custom priority list. (Added this previously so I can add custom sorting for operation properties for the linter later)

**Comment by dblock** [comment]
> We should also alow `--fix` option in the linter to auto fix issues like this.

https://github.com/opensearch-project/opensearch-api-specification/issues/327
