### ISSUE TITLE
[BUG] CAT endpoints response bodies' content-types are `application/json`

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#293]
While the vast majority of OpenSearch endpoints' response bodies are in JSON format, CAT endpoints return tabular data as plaintext instead. The spec currently uses `application/json` for these endpoints, which is incorrect.

**Comment by Xtansia** [comment]
They can and will return JSON if you pass `?format=json` which is what a number of the language clients are hardcoded to do

**Comment by dblock** [comment]
Note that https://localhost:9200/_cat?format=json doesn't return JSON. AFAIK there's no way in OpenAPI to say parameter X -> this kind of output, or is there?

**Comment by dblock** [comment]
This was fixed in https://github.com/opensearch-project/opensearch-api-specification/pull/360 and https://github.com/opensearch-project/opensearch-api-specification/pull/357.
