### ISSUE TITLE
[PROPOSAL] Bootstrap API specification from OpenSearch code

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-api-specification#30]
**What kind of business use case are you trying to solve? What are your requirements?**

Looking at the early PRs on this repository it looks like we are hand-creating/editing API specifications. Is that something that could be generated out of OpenSearch code? At least as a bootstrap? This is one half of https://github.com/opensearch-project/OpenSearch/issues/3090.

**What is the problem? What is preventing you from meeting the requirements?**

The amount of work that will be required to write the models/APIs will be significant and potentially error-prone. It doesn't scale. Every time an API changes we will need to remember to update the specification, by hand. We need to turn this around and generate the RESTful implementation from this spec, which is https://github.com/opensearch-project/OpenSearch/issues/3090. 

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**

Until we start doing https://github.com/opensearch-project/OpenSearch/issues/3090, bootstrap the api specification from source

**Comment by dtaivpp** [comment]
@dblock Is the idea here to auto-generate smithy and then convert that to OpenAPI or something along those lines? I am not seeing a whole lot of support for code generation into other languages from smithy.

**Comment by dblock** [comment]
> @dblock Is the idea here to auto-generate smithy and then convert that to OpenAPI or something along those lines? I am not seeing a whole lot of support for code generation into other languages from smithy.

That's one idea.

**Comment by dblock** [comment]
I am going to close this to avoid confusion. What we want is to write the spec once (this repo), then generate both the RESTful API (https://github.com/opensearch-project/OpenSearch/issues/3090) and the clients (https://github.com/opensearch-project/opensearch-clients/issues/19) from spec.

**Comment by dblock** [comment]
> @dblock Is the idea here to auto-generate smithy and then convert that to OpenAPI or something along those lines? I am not seeing a whole lot of support for code generation into other languages from smithy.

Note https://github.com/opensearch-project/opensearch-api-specification/issues/34
