### ISSUE TITLE
[FEATURE] Release artifact permalink

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-api-specification#380]
### Is your feature request related to a problem?

Coming from https://github.com/opensearch-project/opensearch-java/pull/1065#discussion_r1668654405 we are trying to link to an artifact in the main pre-release in https://github.com/opensearch-project/opensearch-api-specification/releases. This repo makes/updates a pre-release with every commit, but doesn't actually make a release, so the pre-release is actually a moving target.

### What solution would you like?

Change the release process to produce artifacts that have permalinks. This could be a product of a build with an artifact or a release that can be permalinked, but we likely don't want to make a release with every build. Eventually we will be making releases that match OpenSearch releases with full API coverage.

### What alternatives have you considered?

Do nothing, have projects download pre-release artifacts. Wait till we have real releases of API specification, or just start making releases.

**Comment by dblock** [comment]
I may have accidentally fixed this in https://github.com/opensearch-project/opensearch-api-specification/pull/397.

That PR has a couple of drawbacks: 

1. The artifact is uploaded to the build workflow which will eventually expire and be deleted I believe. 
2. The artifact is a zip and doesn't look like that can be changed.

**Comment by reta** [comment]
Thanks @dblock , I think that's a good start, ZIPs could be easily dealt with, please feel free to close this one if not needed
