### ISSUE TITLE
[FEATURE] Add strict_allow_templates option for the dynamic mapping parameter

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/opensearch-api-specification#407]
### Is your feature request related to a problem?
After this [PR](https://github.com/opensearch-project/OpenSearch/pull/14555) is merged, we need to update the specification for the dynamic mapping parameter, we should add `strict_allow_templates` here: https://github.com/opensearch-project/opensearch-api-specification/blob/046b7d1c0c05ab472d2b30f4d041a650c5918417/spec/schemas/_common.mapping.yaml#L138

But I also found that currently we don't support `runtime` for that parameter, so we should remove it.

### What solution would you like?

Update the specification for the dynamic mapping parameter.

**Comment by Tokesh** [comment]
i think we can close this issue by #408
