### ISSUE TITLE
[BUG] NodeInfo required fields can be null in some instances

### ISSUE THREAD

**Issue by dancristiancecoi** [opensearch-project/opensearch-api-specification#475]
### What is the bug?
As described in https://github.com/opensearch-project/opensearch-java/issues/1129, some NodeInfo fields (Host, Ip, TransportAddress) that are listed as required can be null when connected to Amazon OpenSearch Service. 

### How can one reproduce the bug?

Perform a NodeInfoRequest (or equivalent) against an Amazon OpenSearch Service cluster. Those fields will be returned empty.  

### Proposed fix
NodeInfo.Host, NodeInfo.Ip, NodeInfo.TransportAddress should not be listed as required in the spec

### Additional context:
Related Issue: 
- https://github.com/opensearch-project/opensearch-java/issues/1129

I can provide a PR if the above proposed fix is acceptable

**Comment by dblock** [comment]
I fixed this in https://github.com/opensearch-project/opensearch-api-specification/pull/483. After that PR the spec runs clean against AOS 2.13.
