### ISSUE TITLE
[BUG][TEST-FRAMEWORK] Version selector not handling patch version correctly

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#500]
A test story was [skipped](https://github.com/opensearch-project/opensearch-api-specification/actions/runs/10357629378/job/28670062845?pr=489#step:7:66) because:
> Skipped because version 2.17.0 does not satisfy >= 2.11, < 3.0.

This is most likely due to `2.17.0` was used instead of `2.17`.

**Comment by dblock** [comment]
I'll take it.

**Comment by dblock** [comment]
Looks like I already fixed it [here](https://github.com/opensearch-project/opensearch-api-specification/pull/483/files#diff-5fdfeeda9cf99e3d36e2e8c3fb434cd7389123d041be602c663fd30eaf149d1dR240) but I'll refactor it with explicit tests.
