### ISSUE TITLE
[FEATURE] Add specs for flow framework APIs

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-api-specification#508]
### Is your feature request related to a problem?

The `/_plugins/_flow_framework` namespace is not included in the specs.

### What solution would you like?

Add specs/tests for flow framework APIs, https://opensearch.org/docs/latest/automating-configurations/api/index/.

### Do you have any additional context?

Part of https://github.com/opensearch-project/opensearch-api-specification/issues/168

**Comment by dbwiddis** [comment]
@junweid62 please comment here so we can assign this to you :)

**Comment by junweid62** [comment]
Sure thing! Commenting now. :)

**Comment by dbwiddis** [comment]
Resolved by #565
