### ISSUE TITLE
[BUG]Change shape query to xy query and add xy point and xy shape to the spec

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/opensearch-api-specification#516]
### What is the bug?
OpenSearch does not support a shape query. Instead, to search cartesian shapes, it supports an [xy query](https://opensearch.org/docs/latest/query-dsl/geo-and-xy/xy/), which works on [xy points](https://opensearch.org/docs/latest/field-types/supported-field-types/xy-point/) and [xy shapes](https://opensearch.org/docs/latest/field-types/supported-field-types/xy-shape/).

We need to change shape query to xy query in the query dsl spec and add xy point and xy shape to the mapping spec.

**Comment by dblock** [comment]
Is this a feature request to OpenSearch core?

**Comment by kolchfa-aws** [comment]
It's a request to update the spec because OpenSearch does not support shape query and it's [present in the spec](https://github.com/opensearch-project/opensearch-api-specification/blob/main/spec/schemas/_common.query_dsl.yaml#L154). Instead, OpenSearch supports an xy query so we should replace "shape" with "xy".

**Comment by kolchfa-aws** [comment]
@dblock I can give it a try if you want to assign this to me

**Comment by kolchfa-aws** [comment]
Additionally, I will correct the geoshape parameters as well (some are deprected)
