### ISSUE TITLE
[BUG][Spec] Incorrect Schema for Search sort:

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#529]
Spawning off of https://github.com/opensearch-project/opensearch-js/issues/850
Please check that ticket for details.

**Comment by crazyfree** [comment]
@nhtruong hey mate, I'm looking the fix or working around here. 
Thanks!

**Comment by nhtruong** [comment]
Xin Chao :D
Did you you say you wanna work on this (if so I'll assigned the ticket to you), or you're waiting for this to be fixed?

**Comment by crazyfree** [comment]
@nhtruong I’m looking for the fix, since I didn’t familiar with the source code yet.
