### ISSUE TITLE
[BUG] missing definition in termsQuery 

### ISSUE THREAD

**Issue by amberzsy** [opensearch-project/opensearch-api-specification#540]
### What is the bug?
[termsQuery](https://github.com/opensearch-project/opensearch-api-specification/blob/19421f502740967e4d6df102f1c5765c53eaa010/spec/schemas/_common.query_dsl.yaml#L1851) has Object without properties defined

**Comment by prudhvigodithi** [comment]
Going over this link https://opensearch.org/docs/latest/query-dsl/term/terms/ and seeing the https://github.com/opensearch-project/opensearch-api-specification code does adding the following make sense?
```
TermsQuery:
  allOf:
    - $ref: '#/components/schemas/QueryBase'
    - type: object
      properties:
        terms:
          type: object
          description: A JSON object containing the field name and either an array of terms or an object for term lookup.
          additionalProperties:
            oneOf:
              - type: array
                items:
                  type: string
                description: Array of terms you wish to find in the specified field.
              - type: object
                properties:
                  index:
                    $ref: '_common.yaml#/components/schemas/IndexName'
                  id:
                    $ref: '_common.yaml#/components/schemas/Id'
                  path:
                    $ref: '_common.yaml#/components/schemas/Field'
                  routing:
                    $ref: '_common.yaml#/components/schemas/Routing'
                description: Object for fetching terms.
      required:
        - terms

```
The `QueryBase` already has boost so dont need to add again to `properties`.

Thank you 
@amberzsy @dblock @getsaurabh02.

**Comment by dblock** [comment]
I would introduce a `Term` for parts of this.

Either way start by writing a test that exercises this API and then the schema.

**Comment by prudhvigodithi** [comment]
Sure, I will raise a PR adding some tests to `TermQuery`, `TermsQuery`  and `TermsSetQuery`, I assume there are no tests for these queries as I dint find anything in https://github.com/opensearch-project/opensearch-api-specification/tree/main/tests/default/_core/search.

Ref:
https://opensearch.org/docs/latest/query-dsl/term/term/
https://opensearch.org/docs/latest/query-dsl/term/terms/ 
https://opensearch.org/docs/latest/query-dsl/term/terms-set/

**Comment by amberzsy** [comment]
> I would introduce a Term for parts of this.

+1

**Comment by nhtruong** [comment]
Seems like the Search API has a lot of holes to patch. This one is related: https://github.com/opensearch-project/opensearch-api-specification/issues/529

I'll look into the old ES spec (right before OS was forked) to see what's missing and cross check with the new features of this API that are unique to OS.

**Comment by prudhvigodithi** [comment]
Thanks @nhtruong, since the PR to add the missing definition for `termsQuery ` is merged can we close this issue and open a new ones for patches that has to be added to Search API?
@dblock @amberzsy

**Comment by dblock** [comment]
Yes, please. Closing this one.

**Comment by amberzsy** [comment]
@prudhvigodithi 

why we use different definition from https://github.com/opensearch-project/opensearch-api-specification/issues/540#issuecomment-2319667883 in the [PR](https://github.com/opensearch-project/opensearch-api-specification/pull/546/files#diff-d6a667333a8a5fb4837620691c2a09249ae064fb549fa193eaa7db4eb856fcd4R283). 

I did quick testing on 

```
TermsQuery:
  allOf:
    - $ref: '#/components/schemas/QueryBase'
    - type: object
      properties:
        terms:
          type: object
          description: A JSON object containing the field name and either an array of terms or an object for term lookup.
          additionalProperties:
            oneOf:
              - type: array
                items:
                  type: string
                description: Array of terms you wish to find in the specified field.
              - type: object
                properties:
                  index:
                    $ref: '_common.yaml#/components/schemas/IndexName'
                  id:
                    $ref: '_common.yaml#/components/schemas/Id'
                  path:
                    $ref: '_common.yaml#/components/schemas/Field'
                  routing:
                    $ref: '_common.yaml#/components/schemas/Routing'
                description: Object for fetching terms.
      required:
        - terms
```

the JSON will be as below, which looks correct. 
```
{
    "terms": 
             "string_key": {
                    "index": "something", 
                    "id": "id_1",
                    ...
               }

}
```

however with 

```
Terms: 
  oneOf:
        - type: array
          items:
            type: string
        - type: object
          properties:
            index:
              $ref: '_common.yaml#/components/schemas/IndexName'
            id:
              $ref: '_common.yaml#/components/schemas/Id'
            path:
              $ref: '_common.yaml#/components/schemas/Field'
            routing:
              $ref: '_common.yaml#/components/schemas/Routing'
          additionalProperties: true
          description: Object for fetching terms.
```

the JSON will be missing <field_name>

**Comment by prudhvigodithi** [comment]
Hey @amberzsy only difference from my [comment](https://github.com/opensearch-project/opensearch-api-specification/issues/540#issuecomment-2319667883) and PR is is just created a new schema `Terms` so that both the `TermsQuery` and `TermsSetQuery` can leverage the `Terms` schema.

**Comment by Xtansia** [comment]
@amberzsy @prudhvigodithi I've just made a fix to correct the position of the `additionalProperties` and `anyOf/oneOf` on the terms query in #564
