### ISSUE TITLE
[FEATURE] Add parameters to Cat API tests

### ISSUE THREAD

**Issue by Jakob3xD** [opensearch-project/opensearch-api-specification#550]
### Is your feature request related to a problem?
Most of the cat API testes lag the parameter `h=*` which is responsible for returning all fields the endpoint provides.
Beside the `bytes` and `time` parameter should also be added to tests as is transforms the returned values.

### What solution would you like?
Add the parameters to the cat api tests.

### What alternatives have you considered?
None

### Do you have any additional context?
None

**Comment by dblock** [comment]
@Jakob3xD are you going to try and contribute this one?

**Comment by Jakob3xD** [comment]
> @Jakob3xD are you going to try and contribute this one?

Yes, MR is nearly finished.
