### ISSUE TITLE
[BUG] Test with parameter `expand_wildcards` set to none does not return data

### ISSUE THREAD

**Issue by Jakob3xD** [opensearch-project/opensearch-api-specification#554]
### What is the bug?
We have tests that set the parameter `expand_wildcards: none`, which makes the tests useless as the requests does not return useful content.

### How can one reproduce the bug?
```
GET /_stats?expand_wildcards=none
{
  "_shards": {
    "total": 0,
    "successful": 0,
    "failed": 0
  },
  "_all": {
    "primaries": {},
    "total": {}
  },
  "indices": {}
}
```

### What is the expected behavior?
Remove the combination `expand_wildcards` with value `none` so the tests return actual data.

### Do you have any additional context?
Notices this while working on the Human fields MR as the test should have failed due to missing fields.

**Comment by dblock** [comment]
Makes sense. To keep in mind that we do want to test the spec, not the functionality of OpenSearch. It's however good to have meaningful tests as we will use those as examples for auto-generating documentation.
