### ISSUE TITLE
Model for Search, Index and Cluster related APIs

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-api-specification#63]
This issue covers adding models for core APIs not covered in other related issues:

- [x] Alias API - https://opensearch.org/docs/latest/api-reference/alias/
- [x] Analyze API - https://opensearch.org/docs/latest/api-reference/analyze-apis/perform-text-analysis/
- [x] Count API - https://opensearch.org/docs/latest/api-reference/count/
- [x] Explain API - https://opensearch.org/docs/latest/api-reference/explain/
- [x] MSearch API - https://opensearch.org/docs/latest/api-reference/multi-search/
- [x] Rank-Eval - https://opensearch.org/docs/latest/api-reference/rank-eval/
- [x] Remote info - https://opensearch.org/docs/latest/api-reference/remote-info/
- [x] Scroll API - https://opensearch.org/docs/latest/api-reference/scroll/
- [x] Search API - https://opensearch.org/docs/latest/api-reference/search/
- [x] Tasks API - https://opensearch.org/docs/latest/api-reference/tasks/

**Comment by VachaShah** [comment]
One API model is remaining from the above list - Reload Search Analyzer: https://opensearch.org/docs/latest/api-reference/reload-search-analyzer/

**Comment by Tokesh** [comment]
Hello @VachaShah ! Im ready to work on this issue! :)
If that possible, i can do it in 1-2 days. I need to finish all my another issues!

**Comment by Tokesh** [comment]
> One API model is remaining from the above list - Reload Search Analyzer: https://opensearch.org/docs/latest/api-reference/reload-search-analyzer/

Hello! Ready for your [review](https://github.com/opensearch-project/opensearch-api-specification/pull/119)! Sorry for a bit delay :(

**Comment by Tokesh** [comment]
@VachaShah Hello!
Reload Search Analyzer this API does not work in the OpenSearch. It will be removed from the OpenSearch documentation soon.
You can check details [here](https://github.com/opensearch-project/documentation-website/issues/4284)
I think we should remove it from this issue.

**Comment by VachaShah** [comment]
> @VachaShah Hello! Reload Search Analyzer this API does not work in the OpenSearch. It will be removed from the OpenSearch documentation soon. You can check details [here](https://github.com/opensearch-project/documentation-website/issues/4284) I think we should remove it from this issue.

Thank you @Tokesh! I have removed it from the list above. Closing this issue since all the tasks are done.
