### ISSUE TITLE
Model for CAT APIs

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-api-specification#64]
This issue covers adding models for cat APIs listed below:

- [x] Cat alias - https://opensearch.org/docs/latest/api-reference/cat/cat-aliases/
- [x] Cat allocation - https://opensearch.org/docs/latest/api-reference/cat/cat-allocation/
- [x] Cat count - https://opensearch.org/docs/latest/api-reference/cat/cat-count/
- [x] Cat field data - https://opensearch.org/docs/latest/api-reference/cat/cat-field-data/
- [x] Cat health - https://opensearch.org/docs/latest/api-reference/cat/cat-health/
- [x] Cat indices - https://opensearch.org/docs/latest/api-reference/cat/cat-indices/
- [x] Cat cluster manager - https://opensearch.org/docs/latest/api-reference/cat/cat-cluster_manager/
- [x] Cat nodeattrs - https://opensearch.org/docs/latest/api-reference/cat/cat-nodeattrs/
- [x] Cat nodes - https://opensearch.org/docs/latest/api-reference/cat/cat-nodes/
- [x] Cat pending tasks - https://opensearch.org/docs/latest/api-reference/cat/cat-pending-tasks/
- [x] Cat plugins - https://opensearch.org/docs/latest/api-reference/cat/cat-plugins/
- [x] Cat recovery - https://opensearch.org/docs/latest/api-reference/cat/cat-recovery/
- [x] Cat repositories - https://opensearch.org/docs/latest/api-reference/cat/cat-repositories/
- [x] Cat segments - https://opensearch.org/docs/latest/api-reference/cat/cat-segments/
- [x] Cat shards - https://opensearch.org/docs/latest/api-reference/cat/cat-shards/
- [x] Cat snapshots - https://opensearch.org/docs/latest/api-reference/cat/cat-snapshots/
- [x] Cat tasks - https://opensearch.org/docs/latest/api-reference/cat/cat-tasks/
- [x] Cat templates - https://opensearch.org/docs/latest/api-reference/cat/cat-templates/
- [x] Cat thread pool - https://opensearch.org/docs/latest/api-reference/cat/cat-thread-pool/

**Comment by aabeshov** [comment]
Hello , I am college contributor.  May I  help you with creating CAT Models?

**Comment by VachaShah** [comment]
> Hello , I am college contributor. May I help you with creating CAT Models?

Hi @aabeshov, thank you for your interest! We have PR #91 in the works by @nhtruong which adds these models. @nhtruong Can you add if there is anything @aabeshov can contribute for the cat models?

**Comment by VachaShah** [comment]
Done in #83 and #91
