### ISSUE TITLE
Models for Query DSL APIs

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/opensearch-api-specification#66]
- [ ] Query
- [ ] BoolQuery
- [ ] NewBoolQuery
- [ ] NewWildcardQuery
- [ ] TermsQuery
- [ ] NewTermQuery
- [ ] NewTermsQuery
- [ ] NewExistsQuery
- [ ] NewRangeQuery
- [ ] NewConstantScoreQuery
- [ ] NewQueryStringQuery
- [ ] NewIdsQuery

Most of these APIs are documented [here](https://opensearch.org/docs/latest/opensearch/query-dsl/index/).

**Comment by harshavamsi** [comment]
@Xtansia Can you take a look at adding these APIs into the API spec?

**Comment by Xtansia** [comment]
@harshavamsi the Query DSL isn't a separate REST API, it's the query structure passed to the search API: https://opensearch.org/docs/latest/opensearch/query-dsl/index/
https://opensearch.org/docs/latest/api-reference/search/#request-body
e.g.:
```
GET _search
{
  "query": {
    "multi_match": {
      "query": "QUEEN",
      "fields": ["speaker", "text_entry"]
    }
  }
}
```

**Comment by Xtansia** [comment]
And the structure appears to be already defined: 
https://github.com/opensearch-project/opensearch-api-specification/blob/main/model/_types/query_dsl/abstractions.smithy 

https://github.com/opensearch-project/opensearch-api-specification/blob/main/model/_global/search/structures.smithy#L155

**Comment by harshavamsi** [comment]
Perfect, thanks!
