### ISSUE TITLE
Generate missing models from legacy spec

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#82]
This spawns from https://github.com/opensearch-project/opensearch-api-specification/issues/80

Basically use [legacy spec](https://github.com/opensearch-project/OpenSearch/tree/42058aa76a18f531ceaac7deb4e94944cf02f463/rest-api-spec/src/main/resources/rest-api-spec/api) to generate smithy models so we don't have to fill out 308 operations by hand.

The translator code can be found here: https://github.com/nhtruong/opensearch-smithy-spec-translator

**Comment by nhtruong** [comment]
## Goals
We chose maintaining OpenSearch API Spec via Smithy, even though the end-result is standard OpenAPI spec, mainly for its maintainability. So, the generated Smithy Spec should take advantage of Smithy unique features while assure that the models can still be properly translated to OpenAPI:
- Each OpenSearch action, each comprised of one or many API operations, are grouped into folders. For example, the smithy files for `indicies.create` action will be stored in `./model/indices/create` folder. (This grouping is impossible with OpenAPI 3.1, one of many reasons we chose Smithy)
- Each action has 2 smithy files:
  - `operations.smithy`: Describes the operations of said action
  - `structures.smithy`: Describes the structures of the Inputs and Outputs of the operations.
- Most parameters are not only shared within the operations of the same action, but they are also reused in other actions. The parameter definitions, therefore, are stored in common locations for resuse. For example, `common_booleans.smithy` and `common_string_lists.smithy`

**Comment by reta** [comment]
@nhtruong the choice of Smithy is still not obvious, specifically taking into account plugins and extensions, I believe there are compelling arguments to use OpenAPI 3.0+ directly [1], without Smithy shim.

[1] https://github.com/opensearch-project/opensearch-clients/issues/55

**Comment by nhtruong** [comment]
@reta I'm still drafting this comment and accidentally hit `Comment`. Still editing it now. It will be a bit clearer. As discussed in https://github.com/opensearch-project/opensearch-api-specification/issues/80, the end result will be OpenAPI 3.1. We're only using smithy, for now at least, as a device to backfill missing info (like Output schemas, and Body schemas), because it's easier to do so.

**Comment by VachaShah** [comment]
Reopening this issue, since there is a part 2 for the PR.
