### ISSUE TITLE
[BUG] Gradle build failed

### ISSUE THREAD

**Issue by Tokesh** [opensearch-project/opensearch-api-specification#94]
### What is the bug?
When I ran the gradle through the terminal as in the README, it gave me an [error](https://scans.gradle.com/s/c5us57wqt6jdu) and I could not build it.
But when I opened this project through IntelliJ IDEA -  he built for me and downloaded everything that is necessary for the project. Maybe the README does not contain the complete command for the build?

### How can one reproduce the bug?
`./gradlew build` in terminal from project path
<img width="571" alt="image" src="https://user-images.githubusercontent.com/78027392/236607914-80057dcd-cd9b-40ee-affb-08cd4c0aeb64.png">

### What is your host/environment?

MacOS 12.6
Oracle OpenJDK Runtime Environment 19.0.2+7-44
Gradle 7.6
Kotlin 1.7.10
Groovy 3.0.13
JVM 17.0.6

### Screenshot from IntelliJ IDEA
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/78027392/236608315-5c8649dd-71c5-4012-89c6-fc853b8602d4.png">

Maybe this is a small mistake, but if it is important - I can try to solve it.

**Comment by Xtansia** [comment]
The Gradle wrapper in this repo is `7.5.1` and that version does not support JDK 19, which results in this class file major version error:
<img width="1511" alt="Screenshot 2023-05-08 at 9 12 18 AM" src="https://user-images.githubusercontent.com/1222964/236702807-4eccf477-ecc3-4729-a6f8-43acc71a78d3.png">

Solutions are to either ensure Gradle runs under JDK 18 or lower, or make a PR updating the Gradle wrapper to 7.6

**Comment by Tokesh** [comment]
> The Gradle wrapper in this repo is `7.5.1` and that version does not support JDK 19, which results in this class file major version error: <img alt="Screenshot 2023-05-08 at 9 12 18 AM" width="1511" src="https://user-images.githubusercontent.com/1222964/236702807-4eccf477-ecc3-4729-a6f8-43acc71a78d3.png">
> 
> Solutions are to either ensure Gradle runs under JDK 18 or lower, or make a PR updating the Gradle wrapper to 7.6

Thank you very much for quick response! 
When I studied the developer guide, it was not written there about installing specific versions of the gradle. Maybe this should also be added to warn newbies who will install?

I'm interested in trying to update Gradle wrapper to 7.6
Do you think if I try to update the gradle in the repository it won't affect the rest of the components?

**Comment by Xtansia** [comment]
It should be safe to upgrade as when you create a PR there's a CI job to check the model builds. You can find info about the very easy process for upgrading the wrapper here: https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper

**Comment by Tokesh** [comment]
> It should be safe to upgrade as when you create a PR there's a CI job to check the model builds. You can find info about the very easy process for upgrading the wrapper here: https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper

<img width="570" alt="image" src="https://user-images.githubusercontent.com/78027392/236705407-2cf466f1-cf1b-4f01-a8fb-aedf4b357afe.png">

hooray, that working! Sent a pull request, you can check it out at your free time :)

**Comment by Xtansia** [comment]
Fixed in #95

**Comment by Xtansia** [comment]
Thanks for the PR @Tokesh
