### ISSUE TITLE
[BUG] Local testing problem, not passing all tests

### ISSUE THREAD

**Issue by Tokesh** [opensearch-project/opensearch-api-specification#98]
Hello everyone! It's me again! :) I tried to solve this problem for several days, I didn’t want to somehow distract you from larger features. But the problem has gone to some incomprehensible stage.
### What is the bug?
I tried to local test this repo from [developer guide](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md). 
Initially, [it didn't work for me at all](https://codeshare.io/Ad44Kp). But I noticed that in one of the test runs - [you also use a command](https://github.com/opensearch-project/opensearch-api-specification/actions/runs/4909639257/jobs/8766192845) that disables the TLS check(i think we should add this hint to the developer guide). Used this for myself and the tests started running and responding. But every time I get different results. [Then 6/13 passed, sometimes 4/13, 5/13](https://codeshare.io/X833Oz). Maybe I'm missing something?
I built project, models formatted. Docker is running.
### How can one reproduce the bug?
using developer guide with topic "Local testing" - "Testing model API"

### What is the expected behavior?
Pass 13/13 like on github workflow

### What is your host/environment?
MacOS 12.6
Oracle OpenJDK Runtime Environment 19.0.2+7-44
Gradle 7.6
Kotlin 1.7.10
Groovy 3.0.13
JVM 17.0.6
dredd v14.1.0 (Darwin 21.6.0; x64)
<img width="488" alt="image" src="https://github.com/opensearch-project/opensearch-api-specification/assets/78027392/6ac678d7-0343-4726-b362-248965c6a508">
<img width="1130" alt="image" src="https://github.com/opensearch-project/opensearch-api-specification/assets/78027392/4d77c65d-7b21-493f-8856-f01e04989260">

Maybe this is a small mistake, but if it is important - I can try to solve it.

**Comment by nhtruong** [comment]
@Tokesh thanks for bring this up to our attention. We have also been discussion internally on how to improve the test framework for this repo because the current framework is very tedious to maintain. 

@VachaShah what do you think? Should we wait till we have a better direction before addressing issues like this?

**Comment by VachaShah** [comment]
> @Tokesh thanks for bring this up to our attention. We have also been discussion internally on how to improve the test framework for this repo because the current framework is very tedious to maintain.
> 
> @VachaShah what do you think? Should we wait till we have a better direction before addressing issues like this?

I think till we have a different test framework, lets try to fix what is broken in the current one so that contributors can run tests locally. @Tokesh We would surely appreciate a PR if you have a fix in mind!

**Comment by Tokesh** [comment]
> > @Tokesh thanks for bring this up to our attention. We have also been discussion internally on how to improve the test framework for this repo because the current framework is very tedious to maintain.
> > @VachaShah what do you think? Should we wait till we have a better direction before addressing issues like this?
> 
> I think till we have a different test framework, lets try to fix what is broken in the current one so that contributors can run tests locally. @Tokesh We would surely appreciate a PR if you have a fix in mind!

Okkie, thank you for answer! Currently im working on adding specs for Security plugin API. After that, i'll be happy to work on it

**Comment by dblock** [comment]
@Tokesh What's our status here?

**Comment by nhtruong** [comment]
The legacy test framework has been removed along with smithy.  Closing
